### ISSUE TITLE
Question about <page-query> section

### ISSUE THREAD

**Issue by cannap** [timbenniks/timbenniks2020#1]
Hi, i tried to figure out how you parse the `<page-query>`? i cant find any extended vue loader or what ever :D

**Comment by timbenniks** [comment]
Hey @cannap what exactly do you mean by "parse" the `<page-query>`? 

If you mean to access the data it outputs, you can do this in your Vue `<template>` :`{{ $page.Prismic.<querynamespace>.<field>}}` or in your Vue `<script>`: `this.$page.Prismic.<querynamespace>.<field>`

**Comment by cannap** [comment]
hi i mean 

https://github.com/timbenniks/timbenniks2020/blob/master/src/pages/Writings.vue#L53-L95

**Comment by timbenniks** [comment]
Showing me a file and select a line doesn't really help :) Can you elaborate on the question a bit?

**Comment by cannap** [comment]
i just dont understand where you parse the <page-query> i dont see a custom block for vue-loader :D

**Comment by cannap** [comment]
nvm its a gridsome thing :D 
https://gridsome.org/docs/querying-data/

**Comment by timbenniks** [comment]
I finally understood you. Haha. Yes it is indeed a gridsome thing. Super cool.

**Comment by cannap** [comment]
yea my first trought was damn cool he write a query in a custom block instead of apollo: {...} in vue xD then i checked the package.json no apollo  what ever xD

**Comment by timbenniks** [comment]
If you check the Gridsome source you see how nicely they abstract Apollo away. This made me very happy :)
